name = "webapp"
main = "src/index.ts"
compatibility_date = "2024-04-19"

[[d1_databases]]
binding = "DB"
database_name = "webapp-db"
database_id = "20177a86-dc5f-4c87-989a-0fb7b52eb3b3"

[vars]
BUILD_SERVER_URL = "http://ubuntu@iloveuvania.omraheja.me"
