name = "webapp"
main = "src/index.ts"
compatibility_date = "2024-04-19"
account_id = "0bfab51e8cc50b91033dc21005e8cabc"

routes = [
  { pattern = "api.codeabode.co", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "codeabode"
database_id = "73d68d74-4174-4ad5-8462-c440fb5348f3"

[vars]
BUILD_SERVER_URL = "https://iloveuvania.omraheja.me"
